---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm i
  - npm run build
  when:
    event: pull_request

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.cn-shenzhen.aliyuncs.com/lan_jane/this-year
    registry: registry.cn-shenzhen.aliyuncs.com
    tag: latest
  when:
    event: pull_request

- name: deploy
  image: lan-kube
  commands:
    - kubectl set image deployments/this-year this-year=registry.cn-shenzhen.aliyuncs.com/lan_jane/this-year:latest -n apps
  when:
    event: pull_request

trigger:
  event:
    - pull_request
  branch:
    - master