---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node
  commands:
  - npm i
  - npm run build
  when:
    event: pull_request

- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: registry.cn-shenzhen.aliyuncs.com/lan_jane/this-year
    registry: registry.cn-shenzhen.aliyuncs.com
    tag: latest
  when:
    event: pull_request

- name: deploy
  image: pelotech/drone-rancher
  url: https://k8s.lanhao.name/v3
  access_key: token-svth9
  secret_key: ggqp526k55rmxmdztj6nskfff2cfmhmk24jt9gjghbddl69hxtjbqf
  service: apps/this-year
  docker_image: registry.cn-shenzhen.aliyuncs.com/lan_jane/this-year:latest

trigger:
  event:
    - pull_request
  branch:
    - master